site_name: eConEXG
site_description: SDK for Niantong devices.
repo_name: Niantong-Intelligence/eConEXG
repo_url: https://github.com/Niantong-Intelligence/eConEXG
copyright: Copyright &copy; 2024 <a href=http://econtek.cn/>Niantong Intelligence Technology Co., Ltd.</a>

nav:
  - Home: index.md
  - Devices: 
    - iRecorder: iRecorder.md
    - iSense: iSense.md
    - iFocus: iFocus.md
    - DFocus: DFocus.md
    - eConAlpha: eConAlpha.md
    - Trigger Box: 
      - Wireless: triggerBoxWireless.md
      - Wired: triggerBoxWire.md
    - Light Stimulator: lightStimulator.md
  - Changelog: changelog.md

theme:
  favicon: img/favicon.ico
  logo: img/favicon.ico
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
- search
- mkdocstrings
- include-markdown:
    preserve_includer_indent: true

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Niantong-Intelligence/eConEXG
    # - icon: fontawesome/solid/link #material/web
    #   link: http://econtek.cn/

